"""Add click_count to URL model

Revision ID: 53f2613448cb
Revises: a4a3de9a1833
Create Date: 2024-07-17 21:08:09.149557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f2613448cb'
down_revision: Union[str, None] = 'a4a3de9a1833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('click_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'click_count')
    # ### end Alembic commands ###
